# This is the CUDA-enabled Docker image for cpuserver (Neural MCTS model evaluation server).

# Stage 1: build
FROM nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04 AS builder

WORKDIR /build

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    unzip \
    bzip2 \
    git \
    libssl-dev \
    && apt-get clean

RUN curl -L -O https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5.tar.gz \
    && tar --no-same-owner -xzf cmake-3.30.5.tar.gz \
    && cd cmake-3.30.5 \
    && ./bootstrap --prefix=/opt \
    && make -j$(($(nproc) < 8 ? $(nproc) : 8)) \
    && make install

ENV PATH="${PATH}:/opt/bin"

RUN git clone --recurse-submodules -b v1.66.0 --depth 1 --shallow-submodules https://github.com/grpc/grpc

RUN cd grpc \
    && mkdir -p cmake/build \
    && cd cmake/build \
    && cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/opt ../.. \
    && make -j$(($(nproc) < 8 ? $(nproc) : 8)) \
    && make install

RUN curl -L -O https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2 \
    && tar --no-same-owner -xjf boost_1_86_0.tar.bz2 \
    && cd boost_1_86_0/ \
    && ./bootstrap.sh --prefix=/opt \
    && ./b2 install

RUN curl -L -O https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2 \
    && tar --no-same-owner -xjf jemalloc-5.3.0.tar.bz2 \
    && rm jemalloc-5.3.0.tar.bz2 \
    && cd jemalloc-5.3.0 \
    && ./configure --prefix=/opt \
    && make -j$(($(nproc) < 8 ? $(nproc) : 8)) \
    && make install \
    && cd .. \
    && ldconfig /opt/lib

RUN curl -L -o libtorch.zip https://download.pytorch.org/libtorch/cu121/libtorch-cxx11-abi-shared-with-deps-2.5.0%2Bcu121.zip \
    && unzip -d /opt libtorch.zip \
    && rm libtorch.zip

COPY ./cpp/ ./
COPY ./proto/*.proto ./proto/

RUN protoc -Iproto --cpp_out=. --grpc_out=. --plugin=protoc-gen-grpc=$(which grpc_cpp_plugin) proto/hexz.proto proto/health.proto \
    && mkdir build \
    && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/opt/libtorch/share/cmake;/opt/lib/cmake" .. \
    && make -j4 cpuserver_main

# Stage 2: final image
FROM nvidia/cuda:12.2.2-runtime-ubuntu22.04

WORKDIR /app

COPY --from=builder /opt/lib/libjemalloc.so /opt/lib/libjemalloc.so
COPY --from=builder /opt/libtorch/lib /opt/libtorch/lib
COPY --from=builder /build/build/cpuserver /app/cpuserver

ENTRYPOINT ["/usr/bin/env", "LD_PRELOAD=/opt/lib/libjemalloc.so", "./cpuserver"]
