name: pyhexz
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - pytest
  - numpy
  - h5py
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - cython
  - pytz
  - protobuf
  - gunicorn
  - flask
  - requests
  - grpcio
  - grpcio-tools
